# Generated by Django 5.0.3 on 2024-03-18 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.productcategory'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='Shop_license',
            field=models.FileField(blank=True, upload_to='vendor/license', verbose_name='Licenca da loja'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='logo',
            field=models.ImageField(upload_to='restaurant_logo/', verbose_name='Logotipa loja'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Nome da loja'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='phone',
            field=models.CharField(max_length=500, verbose_name='Telefone da loja'),
        ),
    ]
