# Generated by Django 5.0.3 on 2024-04-03 23:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=500, verbose_name='Endereco')),
                ('total', models.IntegerField()),
                ('status', models.IntegerField(choices=[(1, 'Cozinhando'), (2, 'Pedido Pronto'), (3, 'A caminho'), (4, 'Entregue')], verbose_name='stado')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='criado em')),
                ('picked_at', models.DateTimeField(blank=True, null=True, verbose_name='pegar em')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
            },
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Quantidade')),
                ('sub_total', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Detalhe do pedido',
                'verbose_name_plural': 'Detalhes dos pedidos',
            },
        ),
    ]
